package model;
// Generated 08/08/2015 21:28:56 by Hibernate Tools 4.3.1



/**
 * DetalleVenta generated by hbm2java
 */
public class DetalleVenta  implements java.io.Serializable {


     private Integer id;
     private int fkVenta;
     private int fkProducto;
     private int cantidad;
     private int orden;

    public DetalleVenta() {
    }

    public DetalleVenta(int fkVenta, int fkProducto, int cantidad, int orden) {
       this.fkVenta = fkVenta;
       this.fkProducto = fkProducto;
       this.cantidad = cantidad;
       this.orden = orden;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getFkVenta() {
        return this.fkVenta;
    }
    
    public void setFkVenta(int fkVenta) {
        this.fkVenta = fkVenta;
    }
    public int getFkProducto() {
        return this.fkProducto;
    }
    
    public void setFkProducto(int fkProducto) {
        this.fkProducto = fkProducto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }




}


