package model;
// Generated 08/08/2015 21:28:56 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private Integer id;
     private Date fecha;
     private List <DetalleVenta> detallesVenta;

    public Venta() {
        detallesVenta = new ArrayList<DetalleVenta>();
    }

    public Venta(Date fecha) {
       this.fecha = fecha;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public List<DetalleVenta> getDetallesVenta()
    {
        return detallesVenta;
    }

    public void setDetallesVenta(List<DetalleVenta> detallesVenta)
    {
        this.detallesVenta = detallesVenta;
    }
    



}


